name: MATLAB Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
     
      - name: Install Japanese font
        run: |
          sudo apt-get install fonts-horai-umefont
          
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v1
       
      - name: Run MATLAB command
        uses: matlab-actions/run-command@v1
        with:
          command: listfonts
